apiVersion: v1
kind: Service
metadata:
    name: dvwa-service
    labels: 
      app: dvwa-pod-service
spec:
  selector:
    app: dvwa-pod-template
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80

